import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import svg from "../public/image2.svg";
import Link from "next/link";
import { FaSearch } from "react-icons/fa";
import { GiBinoculars } from "react-icons/gi";
import UploadFileTwoToneIcon from '@mui/icons-material/UploadFileTwoTone';


export default function Home() {
  return (
    <>
        <div className={styles.navbar}>
      
      <div className={styles.nav}>
        <nav>
          <ul>
            <li>
              <Link href="/Jobs"><a>Find Work<GiBinoculars className={styles.binoculars}/></a></Link>
              
              
            </li>
            <li>
             
              <Link href="/Jobs"><a>Post Job<UploadFileTwoToneIcon className={styles.upload} /></a></Link>
           
              
            </li>
            <li>
             
              <Link href="/About"><a>About Us</a></Link>
              
            </li>
          </ul>
        </nav>
        <div className={styles.inputContainer}>
        <input placeholder="Search"/>
        <FaSearch className={styles.searchIcon}/>
        </div>
        
        <nav className={styles.navbarSec} >
          <ul>
            <li className={styles.btn}>
             <Link href="/Login"><a>Login</a></Link>
              
              
            </li>
            <li className={styles.btn}>
             <Link href="/Sign_Up"><a>Sign Up</a></Link>
              
              
            </li>
           
          </ul>
        </nav>
       
       
      
         </div>
      </div>
    <div className={styles.container}>
      <Head>
        <title>Hastle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  

      <main className={styles.main}>
      
      
        
 
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
    </>
  )
}
